apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  JWT_SECRET: YjQ1MTdjYjFmZjcxNTUyZjNhZTlmMjAzNzk2MWM0ODEwOTY4MmU5NzMxNzZlMzM0OWU1MzZjOTAxMzRkNGY1OQ==
  AUTH_DB_PASSWORD: TGxzNHVsdTdmNkt5VWFSaQ==
  DB_PASSWORD: S0MySnJZNWtSVkhaYXhvbQ==
  STRIPE_SECRET_KEY: c2tfdGVzdF9wbGFjZWhvbGRlcg==

#all secrets are tests