spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/${DB_NAME:userservice}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}

  data:
    redis:
      host: redis-cache
      port: 6379