server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:userservice} #changed
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #changed
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

  cache:
    type: redis

logging:
  level:
    org.hibernate.SQL: DEBUG