server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service
  profiles:
    active: local

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cache:
    type: redis

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-service
      auto-offset-reset: earliest

logging:
  level:
    org.hibernate.SQL: DEBUG

app:
  cache:
    expiration-minutes: 20
  kafka:
    topic:
      user-status: user-status-events
      user-created: user-created-events

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
