server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: order-service
  profiles:
    active: local

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-service
      auto-offset-reset: earliest

app:
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:8080/api/v1}
  kafka:
    topic:
      payment-created: payment-created-events

auth:
  jwt:
    secret: ${JWT_SECRET}

resilience4j:
  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
  circuitbreaker:
    instances:
      userService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException

logging:
  level:
    org.hibernate.SQL: DEBUG
