server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: order-service
  profiles:
    active: local

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-service
      auto-offset-reset: earliest

logging:
  level:
    org.hibernate.SQL: DEBUG
