name: User Service CI Pipeline

on:
  push:
    paths:
      - "user-service/**"
    branches: [ "main", "develop" ]
  pull_request:
    paths:
      - "user-service/**"
    branches: [ "main", "develop" ]

jobs:
  pipeline-execution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 23 Environment
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant executable rights for Gradle
        run: chmod +x ./user-service/gradlew

      - name: Step 1 - Build Application
        run: ./user-service/gradlew -p user-service compileJava --no-daemon

      - name: Step 2 - Run Unit and Integration Tests
        run: ./user-service/gradlew -p user-service test jacocoTestReport --no-daemon

      - name: Step 3 - SonarQube Code Analysis
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=market-inno-user-service
            -Dsonar.organization=valldemarxorin
            -Dsonar.sources=user-service/src/main/java
            -Dsonar.tests=user-service/src/test/java
            -Dsonar.coverage.jacoco.xmlReportPaths=user-service/build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.coverage.exclusions=**/dto/**,**/config/**,**/exception/**,**/dao/**,**/*Application.java,**/*MapperImpl.java,**/util/**,**/aspect/**

      - name: Step 4 - Build Final Docker Image Artefact
        run: docker build -t user-service-app:latest ./user-service